### ISSUE TITLE
Ramping should go immediately back to 0

### ISSUE THREAD

**Issue by LoadingPleaseWait** [Impact2585/FRC2016#25]
When the input for movement goes back to 0, the value that gets sent to the `drive` method should immediately go back to 0. This issue is of high importance.

**Comment by LoadingPleaseWait** [comment]
@J0hnCena, are you able to do this?

**Comment by jwong101** [comment]
I have debate tomorrow until sometime after 12, but I'll try to work on it after the tournament.

**Comment by LoadingPleaseWait** [comment]
Resolved by fb8b6fc68dd009d201a9c7ff47a5742d1876f68d.
