### ISSUE TITLE
Full power for intake and arm

### ISSUE THREAD

**Issue by LoadingPleaseWait** [Impact2585/FRC2016#42]
We may find ourselves in a situation in which we want the motors controlling the arm and/or intake to go at 100% for more torque. Make it so that if the driver puts analog input at 100%, the motor(s) that are being controlled by that input try to spin at 100% speed.

**Comment by jwong101** [comment]
Should I add another input that disables the speed multiplier for both if we want high torque?

**Comment by LoadingPleaseWait** [comment]
I don't think that's necessary.

**Comment by LoadingPleaseWait** [comment]
Closed by 312204f1d869ebe0df33941c85467ca1b7b85f85.
