### ISSUE TITLE
Accelerometer

### ISSUE THREAD

**Issue by LoadingPleaseWait** [Impact2585/FRC2016#52]
Add a class called `AccelerometerSystem` which monitors the acceleration of the robot using the MPU 6050 accelerometer/gyro.

**Comment by jwong101** [comment]
Do you want to read the gyro values as well?

**Comment by LoadingPleaseWait** [comment]
Yes

**Comment by LoadingPleaseWait** [comment]
Although, for now we can just read the values for acceleration.

**Comment by jwong101** [comment]
Ok, I'll make the AccelerometerSystem tomorrow. I'll try to see if I can add processing, but if I don't finish, I'll try to finish it when I get back.

**Comment by LoadingPleaseWait** [comment]
Closed by acf5856d22d9f20be794d850d0c2fb54d5d239fa.
